# Generated by Django 2.0.7 on 2018-07-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20180713_0651'),
        ('users', '0002_customuser_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='choices',
            field=models.ManyToManyField(to='polls.Choice'),
        ),
    ]
