# Generated by Django 2.0.7 on 2018-07-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='choices',
            field=models.ManyToManyField(related_name='votersID', to='polls.Choice'),
        ),
    ]
