# Generated by Django 2.0.7 on 2018-07-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180713_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='scoreBus',
            field=models.FloatField(default=1000),
        ),
        migrations.AddField(
            model_name='customuser',
            name='scoreDev',
            field=models.FloatField(default=1000),
        ),
        migrations.AddField(
            model_name='customuser',
            name='scoreManag',
            field=models.FloatField(default=1000),
        ),
        migrations.AddField(
            model_name='customuser',
            name='scoreOp',
            field=models.FloatField(default=1000),
        ),
        migrations.AddField(
            model_name='customuser',
            name='scoreStrat',
            field=models.FloatField(default=1000),
        ),
        migrations.AddField(
            model_name='customuser',
            name='scoreTech',
            field=models.FloatField(default=1000),
        ),
    ]
