# Generated by Django 2.0.7 on 2018-07-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180716_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='isPartener2',
            new_name='isPartner2',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='isStaff',
            field=models.BooleanField(default=True),
        ),
    ]
