# Generated by Django 2.0.7 on 2018-07-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180717_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='isAdmin',
            field=models.BooleanField(default=False, verbose_name='Admin'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='isManager',
            field=models.BooleanField(default=False, verbose_name='Manager'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='isPartner',
            field=models.BooleanField(default=False, verbose_name='Partner'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='isPartner2',
            field=models.BooleanField(default=False, verbose_name='Partner 2'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='isSeniorDirector',
            field=models.BooleanField(default=False, verbose_name='Senior Director'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='isStaff',
            field=models.BooleanField(default=True, verbose_name='Staff'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='score',
            field=models.FloatField(default=1000, verbose_name='General'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='scoreBus',
            field=models.FloatField(default=1000, verbose_name='Business'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='scoreDev',
            field=models.FloatField(default=1000, verbose_name='Development'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='scoreManag',
            field=models.FloatField(default=1000, verbose_name='Management'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='scoreOp',
            field=models.FloatField(default=1000, verbose_name='Operations'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='scoreStrat',
            field=models.FloatField(default=1000, verbose_name='Strategy'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='scoreTech',
            field=models.FloatField(default=1000, verbose_name='Tech'),
        ),
    ]
