# Generated by Django 2.0.7 on 2018-07-13 06:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0003_auto_20180712_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='votersID',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='choice',
            name='votes',
            field=models.FloatField(default=0),
        ),
    ]
