# Generated by Django 2.0.7 on 2018-07-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20180713_0632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votersID',
        ),
        migrations.AlterField(
            model_name='choice',
            name='voters',
            field=models.CharField(blank=True, default='', max_length=4000),
        ),
    ]
