# Generated by Django 2.0.7 on 2018-07-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20180713_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='isacurate',
            field=models.BooleanField(default=False),
        ),
    ]
