# Generated by Django 2.0.7 on 2018-07-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_choice_isacurate'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='theme',
            field=models.CharField(choices=[('General', 'General'), ('Business', 'Business'), ('Development', 'Development'), ('Operation', 'Operations'), ('Strategy', 'Strategy'), ('Techno', 'Techno'), ('Management', 'Management')], default='General', max_length=200),
        ),
    ]
