# Generated by Django 2.0.7 on 2018-07-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_question_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='isManagers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='isPartener2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='isPartner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='isSeniorDirector',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='isStaff',
            field=models.BooleanField(default=False),
        ),
    ]
