# Generated by Django 2.0.7 on 2018-07-17 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20180717_0727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='ispartener2',
            new_name='ispartner2',
        ),
    ]
