# Generated by Django 2.0.7 on 2018-07-17 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20180717_0855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='ismanagers',
            new_name='ismanager',
        ),
    ]
