# Generated by Django 2.0.7 on 2018-07-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20180717_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='isacurate',
            field=models.BooleanField(default=False, verbose_name='Is the acurate answer'),
        ),
        migrations.AlterField(
            model_name='question',
            name='isadmin',
            field=models.BooleanField(default=True, verbose_name='For Admins'),
        ),
        migrations.AlterField(
            model_name='question',
            name='ismanager',
            field=models.BooleanField(default=True, verbose_name='For Managers'),
        ),
        migrations.AlterField(
            model_name='question',
            name='ispartner',
            field=models.BooleanField(default=True, verbose_name='For Partners'),
        ),
        migrations.AlterField(
            model_name='question',
            name='ispartner2',
            field=models.BooleanField(default=True, verbose_name='For Partners 2'),
        ),
        migrations.AlterField(
            model_name='question',
            name='isseniordirector',
            field=models.BooleanField(default=True, verbose_name='For Senior Directors'),
        ),
        migrations.AlterField(
            model_name='question',
            name='isstaff',
            field=models.BooleanField(default=True, verbose_name='For Staff'),
        ),
    ]
